/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as GraciasRouteImport } from './routes/gracias'
import { Route as ComprarRouteImport } from './routes/comprar'
import { Route as IndexRouteImport } from './routes/index'

const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const GraciasRoute = GraciasRouteImport.update({
  id: '/gracias',
  path: '/gracias',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprarRoute = ComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comprar': typeof ComprarRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comprar': typeof ComprarRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comprar': typeof ComprarRoute
  '/gracias': typeof GraciasRoute
  '/privacidad': typeof PrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/comprar' | '/gracias' | '/privacidad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comprar' | '/gracias' | '/privacidad'
  id: '__root__' | '/' | '/comprar' | '/gracias' | '/privacidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprarRoute: typeof ComprarRoute
  GraciasRoute: typeof GraciasRoute
  PrivacidadRoute: typeof PrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gracias': {
      id: '/gracias'
      path: '/gracias'
      fullPath: '/gracias'
      preLoaderRoute: typeof GraciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprar': {
      id: '/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof ComprarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprarRoute: ComprarRoute,
  GraciasRoute: GraciasRoute,
  PrivacidadRoute: PrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
